# Generated by Django 4.2.6 on 2023-10-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallintasivusto', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laitteet',
            new_name='LaiteKategoria',
        ),
        migrations.AlterModelOptions(
            name='laite',
            options={'verbose_name_plural': 'Laitteet'},
        ),
        migrations.AlterModelOptions(
            name='laitekategoria',
            options={'verbose_name_plural': 'LaiteKategoriat'},
        ),
    ]
