# Generated by Django 4.2.6 on 2023-10-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallintasivusto', '0003_kohde_alter_kategoria_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kohde',
            name='credentials',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='kohde',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
