# Generated by Django 4.2.6 on 2023-10-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallintasivusto', '0004_kohde_credentials_alter_kohde_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SivunLataukset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
